name: Java CI
on: [push]

jobs:
  job-name:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
      - uses: actions/checkout@v2
      - uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
      - uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile2
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
